"""add is_verified and is_active col to user table

Revision ID: 2ed80692dcea
Revises: 56b4d4ed9d11
Create Date: 2026-07-06 00:55:14.291348

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ed80692dcea"
down_revision: Union[str, Sequence[str], None] = "56b4d4ed9d11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("is_verified", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.add_column(
        "user",
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_active")
    op.drop_column("user", "is_verified")
    # ### end Alembic commands ###
